language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SKELETON_VERSION="^3.4"
        - php: 7.1
          env: SKELETON_VERSION="^4.0"

before_install:
    - phpenv config-rm xdebug.ini || true
    - export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/uxgood/recipes/${TRAVIS_PULL_REQUEST}
    - export PACKAGES=$(curl -s $SYMFONY_ENDPOINT | sed -En 's/.*composer req "([^"]+)".*/\1/p' | | sed 's/\^[0-9.a-zA-Z]*/\0@dev/')

install:
    - composer create-project "symfony/skeleton:${SKELETON_VERSION}" flex
    - cd flex

script:
    - composer req "${PACKAGES}"
